# Generated by Django 5.2.17 on 2026-09-24 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('metal', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver'), ('palladium', 'Palladium')], default='gold', max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('pieces', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('plain', 'Plain'), ('jurao', 'Jurao')], default='plain', max_length=10)),
                ('size', models.CharField(blank=True, max_length=30)),
                ('design', models.CharField(blank=True, max_length=100)),
                ('nature', models.CharField(choices=[('new', 'New'), ('transfer', 'Transfer'), ('karigar', 'Karigar'), ('old', 'Old')], default='new', max_length=10)),
                ('source_type', models.CharField(choices=[('opening_stock', 'Opening stock'), ('current_purchase', 'Current purchase')], default='current_purchase', max_length=20)),
                ('book_no', models.CharField(blank=True, max_length=30)),
                ('page_no', models.CharField(blank=True, max_length=20)),
                ('gross_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('big_stone_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pd_diamond_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('extra_less_gold', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('gold_weight', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10)),
                ('ratti_kaat', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('pasa', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gold_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('extra_costs', models.DecimalField(decimal_places=2, default=0, help_text='Beads, dropper, stones, diamond, silver', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('sold', 'Sold'), ('sr_refine', 'Sent to refine'), ('returned', 'Returned'), ('transferred', 'Transferred')], default='in_stock', max_length=12)),
                ('photo', models.ImageField(blank=True, max_length=500, null=True, upload_to='stock/%Y/%m/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='parties.supplier')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='stock_stock_status_84c8a5_idx'), models.Index(fields=['category'], name='stock_stock_categor_1d8790_idx'), models.Index(fields=['metal'], name='stock_stock_metal_d1b668_idx'), models.Index(fields=['purchase_date'], name='stock_stock_purchas_e6832b_idx'), models.Index(fields=['status', 'metal', 'category'], name='stock_stock_status_354724_idx')],
            },
        ),
    ]
