# Generated by Django 5.2.17 on 2026-09-24 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('book_no', models.CharField(blank=True, max_length=30)),
                ('page_no', models.CharField(blank=True, max_length=20)),
                ('share_percent', models.DecimalField(decimal_places=2, default=0, help_text='e.g. 3.5', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal'), ('profit_paid', 'Profit paid')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cash_account', models.CharField(default='shop_cash', max_length=50)),
                ('period_from', models.DateField(blank=True, help_text='Profit period (profit_paid only)', null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('cash_book_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cashbook.cashbookentry')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investors.investor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
