# Generated by Django 5.2.17 on 2026-09-24 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBookEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expenditure')], db_index=True, max_length=1)),
                ('detail', models.CharField(blank=True, help_text='Cash / MBI / Salami ...', max_length=100)),
                ('debited_to', models.CharField(blank=True, help_text='Shop / Home / Refine / person', max_length=100)),
                ('party', models.CharField(blank=True, help_text='Received from / Paid to', max_length=200)),
                ('book_no', models.CharField(blank=True, max_length=30)),
                ('page_no', models.CharField(blank=True, max_length=20)),
                ('pound_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pasa_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('sale', 'Sale'), ('advance', 'Advance'), ('customer_payment', 'Customer payment'), ('supplier_payment', 'Supplier payment'), ('refine', 'Refine'), ('investor', 'Investor'), ('reversal', 'Reversal'), ('import', 'Import')], default='manual', max_length=30)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('cash_account', models.CharField(db_index=True, default='shop_cash', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('day_locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'cash book entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Per cash-account opening/in/out/closing')),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Physical cash counted at close (optional)', max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('locked_at', models.DateTimeField(null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
