# Generated by Django 5.2.17 on 2026-09-24 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbookentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='hoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.headofaccount'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='sub_hoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_entries', to='core.headofaccount'),
        ),
        migrations.AddField(
            model_name='cashbookentry',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayclose',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['hoa'], name='cashbook_ca_hoa_id_5eb5c3_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbookentry',
            index=models.Index(fields=['source_type', 'source_id'], name='cashbook_ca_source__6687a1_idx'),
        ),
    ]
