# Generated by Django 5.2.17 on 2026-09-24 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance brought forward from the old books', max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='parties_cus_name_049eab_idx')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('supplier', 'Supplier'), ('karigar', 'Karigar')], default='supplier', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='parties_sup_name_4a9021_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('labour', 'Karigar labour'), ('adjustment', 'Adjustment (+)'), ('payment', 'Payment'), ('return', 'Return')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gold_pasa', models.DecimalField(blank=True, decimal_places=4, help_text='Gold given/received instead of cash (optional)', max_digits=12, null=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('cash_account', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('cash_book_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cashbook.cashbookentry')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
