# Generated by Django 5.2.17 on 2026-09-24 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0002_initial'),
        ('parties', '0002_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('customer_name', models.CharField(blank=True, help_text='Walk-in customer name', max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('legacy_book', models.CharField(blank=True, max_length=30)),
                ('legacy_page', models.CharField(blank=True, max_length=20)),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('old_gold_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('paid', 'Paid'), ('voided', 'Voided')], default='open', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.customer')),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='OldGoldIntake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ratti_kaat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pasa', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deduction', models.DecimalField(decimal_places=2, default=0, help_text='Wastage/testing deduction in PKR', max_digits=12)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent_to_refine', 'Sent to refine'), ('refined', 'Refined')], default='pending', max_length=15)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_gold', to='sales.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sale', 'Sale payment'), ('advance', 'Advance'), ('receivable', 'Payment against balance')], default='sale', max_length=12)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('card', 'Card'), ('advance', 'Adjusted from advance')], default='cash', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(db_index=True)),
                ('cash_account', models.CharField(default='shop_cash', max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Bank/card reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('cash_book_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cashbook.cashbookentry')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='parties.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.invoice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('ratti_kaat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pasa', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('gold_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('making_mode', models.CharField(choices=[('fixed', 'Fixed amount'), ('per_gram', 'Per gram'), ('per_tola', 'Per tola'), ('percent', '% of gold value')], default='fixed', max_length=10)),
                ('making_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('making_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stone_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='stock.stockitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_4e3758_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='sales_invoi_custome_32572e_idx'),
        ),
    ]
