# Generated by Django 5.2.17 on 2026-09-24 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbook', '0002_initial'),
        ('sales', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefineLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('refiner', models.CharField(help_text='e.g. MH Lab', max_length=100)),
                ('weight_sent', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('expected_pasa', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('pasa_returned', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_cash_account', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('sent', 'At refiner'), ('returned', 'Returned')], default='sent', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('cash_book_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cashbook.cashbookentry')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefineLotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('pasa', models.DecimalField(decimal_places=4, max_digits=12)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refining.refinelot')),
                ('old_gold_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refine_items', to='sales.oldgoldintake')),
                ('stock_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refine_items', to='stock.stockitem')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('old_gold_intake__isnull', True), ('stock_item__isnull', False)), models.Q(('old_gold_intake__isnull', False), ('stock_item__isnull', True)), _connector='OR'), name='refine_item_exactly_one_source')],
            },
        ),
    ]
