# Generated by Django 5.2.17 on 2026-09-24 06:50

import core.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(default='New Al-Noor Jewellers', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('code_prefixes', models.JSONField(default=core.models.default_code_prefixes)),
                ('cash_accounts', models.JSONField(default=core.models.default_cash_accounts)),
                ('default_discount_limit_manager', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('default_discount_limit_staff', models.DecimalField(decimal_places=2, default=2000, max_digits=12)),
                ('receipt_footer_text', models.TextField(default='Thank you for your purchase. Please keep this receipt for exchange or return.')),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('sale_gold_basis', models.CharField(choices=[('pasa', 'Pasa (pure-gold equivalent)'), ('weight', 'Gold weight')], default='pasa', max_length=10)),
                ('zakat_rate_percent', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'shop settings',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('salesperson', 'Salesperson')], default='salesperson', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('discount_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GoldRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('buy_rate_per_tola', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sell_rate_per_tola', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(max_length=64)),
                ('entity_repr', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('void', 'Void'), ('login', 'Login'), ('lock', 'Lock'), ('unlock', 'Unlock'), ('other', 'Other')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_auditl_entity__244637_idx'), models.Index(fields=['user'], name='core_auditl_user_id_2ff9b7_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='HeadOfAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('I', 'Income'), ('E', 'Expenditure')], max_length=1)),
                ('report_group', models.CharField(blank=True, help_text='shop_expenses | home | zakat | refine | oj | shopjew ...', max_length=50)),
                ('is_private', models.BooleanField(default=False, help_text='Hidden from salespeople (home, zakat, investors ...)')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.headofaccount')),
            ],
            options={
                'ordering': ['type', 'name'],
                'unique_together': {('name', 'parent', 'type')},
            },
        ),
    ]
